[build]
  base = "flutter_dilanscissors"
  publish = "build/web"
  command = "if [ ! -d _flutter ]; then git clone https://github.com/flutter/flutter.git --depth 1 -b stable _flutter; fi && export PATH=$PATH:$PWD/_flutter/bin && flutter doctor && flutter build web --release"